services:
  twitter-feeder-collector:
    image: twitter-feeder-collector
    build:
      context: ./Collector
      dockerfile: Collector.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
        - twitter-feeder
networks:
  twitter-feeder:
    driver: bridge