use chrono::{Duration, Local};

use crate::custom_widgets::Tweet;

pub fn create_fake_data() -> Vec<Tweet> {
    let now = Local::now().naive_local();
    vec![
        Tweet {
            name: "Paul Graham".into(),
            handle: "@paulg".into(),
            time: now - Duration::minutes(2),
            body: "The best way to get started on a hard project is to do a tiny, embarrassingly small version of it first. The best way to get started on a hard project is to do a tiny, embarrassingly small version of it first. ||| The best way to get started on a hard project is to do a tiny, embarrassingly small version of it first. The best way to get started on a hard project is to do a tiny, embarrassingly small version of it first.".into(),
            replies: 42,
            retweets: 219,
            likes: 1200,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Sindre Sorhus".into(),
            handle: "@sindresorhus".into(),
            time: now - Duration::minutes(14),
            body: "Just released a new CLI tool for converting any image to ASCII art. Because why not. npm i -g asciiify".into(),
            replies: 18,
            retweets: 87,
            likes: 340,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Julia Evans".into(),
            handle: "@b0rk".into(),
            time: now - Duration::minutes(31),
            body: "things i have learned about DNS: it is complicated, it is everywhere, and it is always DNS.".into(),
            replies: 91,
            retweets: 504,
            likes: 3700,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Cassidy Williams".into(),
            handle: "@cassidoo".into(),
            time: now - Duration::hours(1),
            body: "reminder that \"it works on my machine\" is still a valid debugging strategy if you ship your machine".into(),
            replies: 55,
            retweets: 231,
            likes: 2100,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Theo Browne".into(),
            handle: "@t3dotgg".into(),
            time: now - Duration::hours(2),
            body: "TypeScript is just JavaScript with a spell checker that also occasionally yells at you for things that are completely fine".into(),
            replies: 130,
            retweets: 612,
            likes: 4800,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Primeagen".into(),
            handle: "@ThePrimeagen".into(),
            time: now - Duration::hours(3),
            body: "Vim motions are not about speed. They are about never leaving the keyboard. Flow state is the goal.".into(),
            replies: 77,
            retweets: 389,
            likes: 2900,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Kelsey Hightower".into(),
            handle: "@kelseyhightower".into(),
            time: now - Duration::hours(5),
            body: "Kubernetes is not the destination. It is the bus you take to get somewhere. Most people forget to get off.".into(),
            replies: 203,
            retweets: 881,
            likes: 6100,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Dan Abramov".into(),
            handle: "@dan_abramov".into(),
            time: now - Duration::hours(6),
            body: "The reason React re-renders so much is because you told it to. That's not a bug, that's the API.".into(),
            replies: 88,
            retweets: 430,
            likes: 3100,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Guillermo Rauch".into(),
            handle: "@rauchg".into(),
            time: now - Duration::hours(7),
            body: "Ship early. Ship often. Ship broken things and fix them in public. That's how trust is built.".into(),
            replies: 64,
            retweets: 310,
            likes: 2700,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Sarah Drasner".into(),
            handle: "@sarah_edo".into(),
            time: now - Duration::hours(8),
            body: "CSS is a programming language. It has logic, conditionals, variables, and loops. Stop being mean to it.".into(),
            replies: 112,
            retweets: 560,
            likes: 4200,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Kent C. Dodds".into(),
            handle: "@kentcdodds".into(),
            time: now - Duration::hours(9),
            body: "Write tests. Not too many. Mostly integration. The ratio matters more than the count.".into(),
            replies: 49,
            retweets: 278,
            likes: 2400,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Evan You".into(),
            handle: "@youyuxi".into(),
            time: now - Duration::hours(10),
            body: "Vue 4 is not a rewrite. It's a refinement. We learned from every mistake in Vue 2 and Vue 3 and we're not making them again.".into(),
            replies: 73,
            retweets: 401,
            likes: 3500,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Rich Harris".into(),
            handle: "@Rich_Harris".into(),
            time: now - Duration::hours(11),
            body: "The virtual DOM is pure overhead. I said what I said. Svelte compiles it away and you don't miss it.".into(),
            replies: 201,
            retweets: 780,
            likes: 5900,
            liked: true,
            retweeted: true,
        },
        Tweet {
            name: "Wes Bos".into(),
            handle: "@wesbos".into(),
            time: now - Duration::hours(12),
            body: "Hot take: most developers should learn the platform before reaching for a framework. The web is incredibly capable now.".into(),
            replies: 95,
            retweets: 470,
            likes: 3800,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Scott Tolinski".into(),
            handle: "@stolinski".into(),
            time: now - Duration::hours(13),
            body: "Bun is genuinely fast. I benchmarked it against Node and the gap is not close. Give it a real shot.".into(),
            replies: 38,
            retweets: 190,
            likes: 1600,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Lee Robinson".into(),
            handle: "@leeerob".into(),
            time: now - Duration::hours(14),
            body: "Edge computing isn't about speed alone. It's about running code close to your data and your users simultaneously.".into(),
            replies: 29,
            retweets: 155,
            likes: 1300,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Addy Osmani".into(),
            handle: "@addyosmani".into(),
            time: now - Duration::hours(15),
            body: "Performance is a feature. Every 100ms of latency costs you conversions. Measure, optimize, repeat.".into(),
            replies: 67,
            retweets: 345,
            likes: 2900,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "DHH".into(),
            handle: "@dhh".into(),
            time: now - Duration::hours(16),
            body: "The complexity that JavaScript has accumulated over the last decade is a collective punishment for abandoning simplicity.".into(),
            replies: 310,
            retweets: 920,
            likes: 7200,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Charity Majors".into(),
            handle: "@mipsytipsy".into(),
            time: now - Duration::hours(17),
            body: "Observability is not monitoring. Monitoring tells you something is wrong. Observability tells you why.".into(),
            replies: 54,
            retweets: 288,
            likes: 2500,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Linus Torvalds".into(),
            handle: "@Linus__Torvalds".into(),
            time: now - Duration::hours(18),
            body: "Bad programmers worry about the code. Good programmers worry about data structures and their relationships.".into(),
            replies: 445,
            retweets: 1800,
            likes: 14000,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Antirez".into(),
            handle: "@antirez".into(),
            time: now - Duration::hours(19),
            body: "Redis was never meant to replace your database. It was meant to keep your database from collapsing under pressure.".into(),
            replies: 82,
            retweets: 410,
            likes: 3400,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Mitchell Hashimoto".into(),
            handle: "@mitchellh".into(),
            time: now - Duration::hours(20),
            body: "The terminal is still the most productive environment ever created for software developers. Nothing has come close.".into(),
            replies: 99,
            retweets: 490,
            likes: 4100,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Thorsten Ball".into(),
            handle: "@thorstenball".into(),
            time: now - Duration::hours(21),
            body: "Writing an interpreter taught me more about programming than any course or book. Build things that run other things.".into(),
            replies: 41,
            retweets: 210,
            likes: 1900,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Teej DeVries".into(),
            handle: "@teej_dv".into(),
            time: now - Duration::hours(22),
            body: "Neovim is not about keybindings. It's about having a programmable editor that does exactly what you want and nothing else.".into(),
            replies: 66,
            retweets: 330,
            likes: 2800,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "TJ Holowaychuk".into(),
            handle: "@tjholowaychuk".into(),
            time: now - Duration::hours(23),
            body: "The best abstractions are the ones that disappear. If you're always thinking about the abstraction, it's the wrong one.".into(),
            replies: 58,
            retweets: 305,
            likes: 2600,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Jess Frazelle".into(),
            handle: "@jessfraz".into(),
            time: now - Duration::days(1),
            body: "Containers are not VMs. Stop treating them like VMs. The mental model matters enormously for security.".into(),
            replies: 77,
            retweets: 388,
            likes: 3200,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Aaron Patterson".into(),
            handle: "@tenderlove".into(),
            time: now - Duration::days(1),
            body: "Ruby is slow in benchmarks and fast in production. The benchmarks are measuring the wrong things.".into(),
            replies: 103,
            retweets: 512,
            likes: 4400,
            liked: true,
            retweeted: true,
        },
        Tweet {
            name: "Mattt".into(),
            handle: "@mattt".into(),
            time: now - Duration::days(1),
            body: "Swift is the most underrated systems language of the last decade. It deserves far more attention outside Apple's ecosystem.".into(),
            replies: 46,
            retweets: 230,
            likes: 2000,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Chris Lattner".into(),
            handle: "@clattner_llvm".into(),
            time: now - Duration::days(1),
            body: "MLIR is the most important piece of compiler infrastructure built in the last ten years. The ecosystem is just getting started.".into(),
            replies: 88,
            retweets: 445,
            likes: 3700,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Yehuda Katz".into(),
            handle: "@wycats".into(),
            time: now - Duration::days(1),
            body: "Rust's borrow checker isn't hard once you stop fighting it. It's trying to tell you something about your design.".into(),
            replies: 134,
            retweets: 660,
            likes: 5500,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Armin Ronacher".into(),
            handle: "@mitsuhiko".into(),
            time: now - Duration::days(1),
            body: "Python packaging is bad but it's getting better. Give it another two years. The tooling churn is necessary.".into(),
            replies: 158,
            retweets: 730,
            likes: 5800,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Filippo Valsorda".into(),
            handle: "@FiloSottile".into(),
            time: now - Duration::days(2),
            body: "Cryptography is not hard to use correctly if the library makes wrong usage impossible. API design is security.".into(),
            replies: 62,
            retweets: 310,
            likes: 2700,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Xe Iaso".into(),
            handle: "@theprincessxena".into(),
            time: now - Duration::days(2),
            body: "Writing blog posts about what you learned forces you to actually understand it. Explain it or you don't know it.".into(),
            replies: 39,
            retweets: 198,
            likes: 1750,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Fasterthanlime".into(),
            handle: "@fasterthanlime".into(),
            time: now - Duration::days(2),
            body: "The async story in Rust is the most interesting unsolved problem in language design right now. It's worth following closely.".into(),
            replies: 74,
            retweets: 370,
            likes: 3100,
            liked: true,
            retweeted: true,
        },
        Tweet {
            name: "Amos Wenger".into(),
            handle: "@fasterthanlime".into(),
            time: now - Duration::days(2),
            body: "linkers are black magic that every programmer uses every day and almost none of them understand. go read about linkers.".into(),
            replies: 92,
            retweets: 460,
            likes: 3900,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Cliff Click".into(),
            handle: "@cliff_click".into(),
            time: now - Duration::days(2),
            body: "JIT compilation is not cheating. It's just compilation with more information. The JVM proved this decades ago.".into(),
            replies: 48,
            retweets: 245,
            likes: 2100,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Bryan Cantrill".into(),
            handle: "@bcantrill".into(),
            time: now - Duration::days(2),
            body: "Debugging production systems is a craft. dtrace taught an entire generation that you can see inside a live system without stopping it.".into(),
            replies: 105,
            retweets: 525,
            likes: 4500,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Jessie Frazelle".into(),
            handle: "@jessfraz".into(),
            time: now - Duration::days(3),
            body: "Hardware is eating software. FPGAs and custom silicon are coming for the workloads you thought were safely in software forever.".into(),
            replies: 57,
            retweets: 290,
            likes: 2450,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Tef".into(),
            handle: "@tef_ebooks".into(),
            time: now - Duration::days(3),
            body: "The secret to good software architecture is drawing boxes and arrows until something clicks and then writing that down before you forget.".into(),
            replies: 33,
            retweets: 170,
            likes: 1550,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Cindy Sridharan".into(),
            handle: "@copyconstruct".into(),
            time: now - Duration::days(3),
            body: "Testing in production is not reckless. It is the only place where you find out what your software actually does.".into(),
            replies: 68,
            retweets: 340,
            likes: 2900,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Hillel Wayne".into(),
            handle: "@hillelogram".into(),
            time: now - Duration::days(3),
            body: "Formal methods are not just for aerospace. Any system where a bug costs more than the verification is a candidate.".into(),
            replies: 44,
            retweets: 222,
            likes: 1900,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Gary Bernhardt".into(),
            handle: "@garybernhardt".into(),
            time: now - Duration::days(3),
            body: "Functional core, imperative shell. Keep the messy IO at the edges and the clean logic in the center. It scales.".into(),
            replies: 86,
            retweets: 430,
            likes: 3600,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "John Carmack".into(),
            handle: "@ID_AA_Carmack".into(),
            time: now - Duration::days(4),
            body: "Premature optimization is the root of all evil, but that doesn't mean you should ignore performance entirely until the last 5% of the project.".into(),
            replies: 380,
            retweets: 1500,
            likes: 12000,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Fabrice Bellard".into(),
            handle: "@fabrice_bellard".into(),
            time: now - Duration::days(4),
            body: "A fast implementation of X is usually the most complete specification of X. Code does not lie.".into(),
            replies: 71,
            retweets: 360,
            likes: 3000,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Leah Neukirchen".into(),
            handle: "@LeahNeukirchen".into(),
            time: now - Duration::days(4),
            body: "Shell scripting is a real programming language. Most people who complain about it have never read the POSIX spec.".into(),
            replies: 120,
            retweets: 595,
            likes: 5000,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Steve Klabnik".into(),
            handle: "@steveklabnik".into(),
            time: now - Duration::days(4),
            body: "Documentation is not separate from the code. It is part of the code. A function without docs is an incomplete function.".into(),
            replies: 59,
            retweets: 295,
            likes: 2550,
            liked: true,
            retweeted: true,
        },
        Tweet {
            name: "James Munns".into(),
            handle: "@bitshiftmask".into(),
            time: now - Duration::days(5),
            body: "Embedded Rust is ready for production. The ecosystem caught up. You can write safe firmware without sacrificing performance.".into(),
            replies: 36,
            retweets: 182,
            likes: 1600,
            liked: false,
            retweeted: false,
        },
        Tweet {
            name: "Raph Levien".into(),
            handle: "@raphlinus".into(),
            time: now - Duration::days(5),
            body: "GPU compute is not just for machine learning. Rendering, physics, and data processing all benefit enormously from thinking in parallel.".into(),
            replies: 52,
            retweets: 265,
            likes: 2250,
            liked: true,
            retweeted: false,
        },
        Tweet {
            name: "Niko Matsakis".into(),
            handle: "@nikomatsakis".into(),
            time: now - Duration::days(5),
            body: "Lifetimes in Rust are not about memory. They are about relationships between references. The naming was an accident of history.".into(),
            replies: 145,
            retweets: 710,
            likes: 5900,
            liked: false,
            retweeted: true,
        },
        Tweet {
            name: "Manish Goregaokar".into(),
            handle: "@ManishEarth".into(),
            time: now - Duration::days(5),
            body: "Unicode is solved. Yes there are edge cases. Yes it handles them. No, rolling your own encoding is not the answer. Unicode is solved. Yes there are edge cases. Yes it handles them. No, rolling your own encoding is not the answer. Unicode is solved. Yes there are edge cases. Yes it handles them. No, rolling your own encoding is not the answer.".into(),
            replies: 178,
            retweets: 850,
            likes: 7100,
            liked: true,
            retweeted: false,
        },
    ]
}
